namespace Tsump.Services;

public class LanguageService
{
    private string _language = "nl"; // Default to Dutch

    public string Language => _language;
    public bool IsDutch => _language == "nl";
    public bool IsEnglish => _language == "en";

    public event Action? OnLanguageChanged;

    public void SetLanguage(string language)
    {
        if (_language != language)
        {
            _language = language;
            OnLanguageChanged?.Invoke();
        }
    }

    public string Get(string key)
    {
        if (_language == "nl" && Dutch.TryGetValue(key, out var nl))
            return nl;
        if (_language == "en" && English.TryGetValue(key, out var en))
            return en;
        return key;
    }

    public string FormatDate(DateTime date)
    {
        var day = Get(date.DayOfWeek.ToString());
        var month = Get($"Month{date.Month}");
        return $"{day} {date.Day} {month} {date.Year}";
    }

    // ── Dutch ──────────────────────────────────────────────
    private static readonly Dictionary<string, string> Dutch = new()
    {
        // Mode selection
        ["SelectMode"] = "Kies modus",
        ["WeeklyMode"] = "Clubavond",
        ["TournamentMode"] = "Toernooi",
        ["WeeklyModeDesc"] = "Wekelijkse zittingen voor leden en gasten.",
        ["TournamentModeDesc"] = "Toernooien met eenmalige inschrijving.",
        ["SwitchMode"] = "Wissel modus",

        // App update prompt (AppUpdateBanner)
        ["UpdateAvailable"] = "Er is een nieuwe versie. Sluit de app af en open opnieuw om bij te werken.",
        ["UpdateDismiss"] = "OK",

        // Tournament sub-nav
        ["TournamentParticipants"] = "Deelnemers",
        ["TournamentAssignments"] = "Tafels",
        ["TournamentGuidesheets"] = "Gidsbriefjes",

        // Nav / Layout
        ["Home"] = "Home",
        ["Members"] = "Leden",
        ["WeeklySession"] = "Zitting",
        ["History"] = "Geschiedenis",
        ["MeetingMatrix"] = "Ontmoetingen",
        ["CompetitionRanking"] = "Competitiestand",
        ["ClubManager"] = "Clubbeheer",
        ["MahjongclubTsumo"] = "Mahjongclub Tsumo!",

        // Home page
        ["WelcomeTo"] = "Welkom bij Tsumo!",
        ["ManageMembers"] = "Leden beheren",
        ["MembersDesc"] = "Leden toevoegen en bewerken",
        ["StartSession"] = "Zitting aanmaken",
        ["WeeklySessionDesc"] = "Aanwezigheid bijhouden en tafels indelen.",
        ["ViewHistory"] = "Geschiedenis",
        ["HistoryDesc"] = "Eerdere zittingen en spelerstatistieken bekijken.",
        ["ViewMatrix"] = "Ontmoetingen",
        ["MeetingMatrixDesc"] = "Bekijk hoe vaak spelers tegen elkaar gespeeld hebben.",
        ["ViewCompetitionRanking"] = "Competitiestand",
        ["CompetitionRankingDesc"] = "Bekijk de gemiddelde scores van de competitie.",
        ["WorkflowHomeDesc"] = "Volg het stappenplan om een zitting voor te bereiden en af te ronden.",
        ["StartWorkflow"] = "Start stappenplan",

        // Members page
        ["ClubMembers"] = "Clubleden",
        ["AddMember"] = "+ Lid toevoegen",
        ["EditMember"] = "Lid bewerken",
        ["AddNewMember"] = "Nieuw lid toevoegen",
        ["Name"] = "Naam",
        ["Email"] = "E-mail",
        ["Phone"] = "Telefoon",
        ["Active"] = "Actief",
        ["Inactive"] = "Inactief",
        ["Joined"] = "Lid sinds",
        ["Status"] = "Status",
        ["Actions"] = "Acties",
        ["Edit"] = "Bewerken",
        ["Remove"] = "Verwijderen",
        ["Save"] = "Opslaan",
        ["SaveAs"] = "Opslaan als…",
        ["Cancel"] = "Annuleren",
        ["NoMembersYet"] = "Nog geen leden. Voeg je eerste clublid toe!",
        ["ImportMembersCsv"] = "Leden importeren (CSV)",
        ["ExportMembersCsv"] = "Leden exporteren (CSV)",
        ["SelectAllMembers"] = "Allen selecteren",
        ["DeselectAllMembers"] = "Allen deselecteren",
        ["ExportSelected"] = "Exporteren",
        ["selected"] = "geselecteerd",
        ["MembersImported"] = "leden geïmporteerd.",
        ["MembersImportError"] = "Ongeldig CSV-formaat. Verwacht: Nummer;Naam;Bondsnummer",
        ["Loading"] = "Laden...",
        ["Total"] = "Totaal",
        ["members"] = "leden",
        ["active"] = "actief",
        ["ExtraThreePlayerTables"] = "Extra 3-spelertafels",
        ["ExtraThreePlayerTablesDesc"] = "Aantal 3-spelertafels buiten de hanchangeschiedenis om.",

        // Weekly Session page
        ["SessionDate"] = "Zittingsdatum",
        ["StartTime"] = "Starttijd",
        ["SessionsOnDate"] = "Hanchans op deze datum",
        ["NewSession"] = "Nieuwe hanchan",
        ["AddHanchan"] = "Hanchan toevoegen",
        ["NoTime"] = "Geen tijd",
        ["SwapPlayers"] = "Wisselen",
        ["Selected"] = "Geselecteerd",
        ["ClearSelection"] = "Selectie wissen",
        ["CopyToClipboard"] = "Kopiëren naar klembord",
        ["Copied"] = "Gekopieerd!",
        ["Copy"] = "Kopiëren",
        ["Print"] = "Afdrukken",
        ["Download"] = "Downloaden",
        ["Export"] = "Exporteren",
        ["ExportAssignments"] = "Indeling exporteren",
        ["ExportScoresheets"] = "Scoreformulieren exporteren",
        ["ExportRankings"] = "Ranglijst exporteren",
        ["OpenPrint"] = "Openen / Afdrukken",
        ["DownloadHtml"] = "Downloaden als HTML",
        ["PrintScoresheets"] = "Afdrukken",
        ["DownloadScoresheets"] = "Downloaden als HTML",
        ["Scoresheets"] = "Scoresheets",
        ["DeleteHanchan"] = "Hanchan Verwijderen",
        ["DeleteHanchanConfirm"] = "Weet je zeker dat je deze hanchan wilt verwijderen?",
        ["YesDelete"] = "Ja, verwijderen",
        ["ConfirmDeletion"] = "Bevestig verwijderen",
        ["Attendance"] = "Aanwezigheid",
        ["present"] = "aanwezig",
        ["of"] = "van",
        ["AllPresent"] = "Allen aanwezig",
        ["AllAbsent"] = "Allen afwezig",
        ["SearchMembers"] = "Leden zoeken...",
        ["GenerateTableAssignments"] = "Tafelindeling maken",
        ["Regenerate"] = "Opnieuw genereren",
        ["CopyTables"] = "Tafelindeling overnemen",
        ["CopyFromHistory"] = "Kopiëren uit geschiedenis",
        ["SelectSessionToCopy"] = "Selecteer een zitting om te kopiëren",
        ["SaveHanchan"] = "Hanchan opslaan",
        ["TableAssignments"] = "Tafelindeling",
        ["AssignmentsAndScores"] = "Indeling en scores",
        ["Assignments"] = "Indeling",
        ["Table"] = "Tafel",
        ["players"] = "spelers",
        ["Unknown"] = "Onbekend",
        ["UnassignedPlayers"] = "speler(s) kon(den) niet worden ingedeeld (niet genoeg voor een groep van 3).",
        ["SessionSaved"] = "Zitting succesvol opgeslagen!",
        ["PastSessionReadOnly"] = "Dit is een afgeronde zitting. Alleen-lezen.",
        ["RegenerateConfirm"] = "Deze hanchan heeft al een tafelindeling. Opnieuw genereren?",
        ["YesRegenerate"] = "Ja, opnieuw",
        ["ChangeParticipantsWarning"] = "De tafelindeling wordt gewist als het aantal deelnemers wijzigt.",
        ["ChangeAttendanceWarning"] = "De tafelindeling wordt gewist als de aanwezigheid wijzigt.",
        ["YesContinue"] = "Doorgaan",
        ["AddMembersFirst"] = "Nog geen leden geregistreerd.",
        ["AddMembersLink"] = "Voeg eerst leden toe",
        ["NoMembersRegistered"] = "Nog geen leden geregistreerd.",

        // History page
        ["SessionHistory"] = "Geschiedenis",
        ["GoTo"] = "Ga naar",
        ["NoSessionsYet"] = "Nog geen zittingen vastgelegd.",
        ["CreateFirstSession"] = "Maak je eerste zitting",
        ["PresentPlayers"] = "Aanwezige spelers",
        ["AbsentPlayers"] = "Afwezige spelers",
        ["PlayerStatistics"] = "Spelerstatistieken",
        ["Player"] = "Speler",
        ["SessionsAttended"] = "Hanchans aanwezig",
        ["TimesAt3Table"] = "Keer aan 3-spelertafel",
        ["TimesAt4Table"] = "Keer aan 4-spelertafel",
        ["table"] = "tafel",
        ["tables"] = "tafels",

        // Meeting Matrix page
        ["MeetingMatrixTitle"] = "Ontmoetingen",
        ["MeetingMatrixSubtitle"] = "Hoe vaak elk paar spelers aan dezelfde tafel heeft gezeten.",
        ["CompetitionRankingTitle"] = "Competitiestand",
        ["CompetitionRankingSubtitle"] = "Gemiddelde score van alle zittingen die meetellen voor de competitie.",
        ["AverageScore"] = "Gemiddelde",
        ["NoScoreData"] = "Er zijn nog geen scores ingevoerd.",
        ["ShowResultsPerDate"] = "Resultaten per datum tonen",
        ["NoSessionData"] = "Nog geen zittingsgegevens.",
        ["Meetings"] = "Ontmoetingen",
        ["Pairs"] = "Paren",

        // Data Management page
        ["DataManagement"] = "Gegevensbeheer",
        ["ExportData"] = "Gegevens exporteren",
        ["ExportDescription"] = "Exporteer alle leden, zittingen en toernooien naar een bestand.",
        ["ExportToFile"] = "Exporteren naar bestand",
        ["ExportSuccess"] = "Gegevens succesvol geëxporteerd!",
        ["ImportData"] = "Gegevens importeren",
        ["ImportDescription"] = "Importeer leden, zittingen en toernooien uit een eerder geëxporteerd bestand. Dit vervangt alle huidige gegevens.",
        ["ImportFromFile"] = "Importeren uit bestand",
        ["ImportConfirm"] = "Let op: importeren vervangt alle huidige gegevens (leden, zittingen en toernooien). Weet je het zeker?",
        ["YesImport"] = "Ja, importeren",
        ["ImportSuccess"] = "Gegevens succesvol geïmporteerd!",
        ["InvalidFileFormat"] = "Ongeldig bestandsformaat. Gebruik een eerder geëxporteerd Tsumo!-bestand.",
        ["FileTooLarge"] = "Bestand is te groot (max 10 MB).",
        ["CurrentDataSummary"] = "Huidige gegevens",
        ["Sessions"] = "Zittingen",

        // Settings page
        ["Settings"] = "Instellingen",
        ["SettingsTabClubEvent"] = "Club bijeenkomst",
        ["SettingsTabTournament"] = "Toernooi",
        ["SettingsTabStyle"] = "Stijl",
        ["StyleIdentity"] = "Clubidentiteit",
        ["StyleColors"] = "Kleuren",
        ["StyleImages"] = "Afbeeldingen",
        ["BrandText"] = "Clubnaam (linksboven)",
        ["WebsiteUrl"] = "Website-URL",
        ["WebsiteLinkLabel"] = "Tekst van websitelink",
        ["PrimaryColor"] = "Primaire kleur",
        ["LinkColor"] = "Linkkleur",
        ["Logo"] = "Logo (linksboven)",
        ["Banner"] = "Banner (startpagina)",
        ["UploadImage"] = "Uploaden",
        ["ImageUrl"] = "Of plak een afbeeldings-URL",
        ["ClearImage"] = "Afbeelding wissen",
        ["ResetStyle"] = "Terug naar neutrale stijl",
        ["ResetStyleConfirm"] = "Alle stijlinstellingen terugzetten naar neutraal?",
        ["YesReset"] = "Ja, terugzetten",
        ["ExportStyle"] = "Stijl exporteren",
        ["ImportStyle"] = "Stijl importeren",
        ["DiscardChanges"] = "Wijzigingen verwerpen",
        ["CommitStyle"] = "Vastleggen",
        ["YesCommit"] = "Ja, vastleggen",
        ["CommitStyleConfirm"] = "Vastleggen overschrijft de opgeslagen stijl definitief. Heb je de huidige stijl niet geëxporteerd, dan kun je die niet meer herstellen. Toch vastleggen?",
        ["UnsavedStyleChanges"] = "Niet-vastgelegde stijlwijzigingen. Klik op Vastleggen om ze te bewaren.",
        ["StyleSaved"] = "Stijl vastgelegd.",
        ["StyleImported"] = "Stijl geladen — klik op Vastleggen om te bewaren.",
        ["InvalidStyleFile"] = "Ongeldig stijlbestand.",
        ["StylePreview"] = "Voorbeeld",
        ["StylePreviewDesc"] = "Zo ziet je keuze eruit. Wijzigingen zijn direct zichtbaar; pas bij Vastleggen worden ze bewaard.",
        ["SampleButton"] = "Voorbeeldknop",
        ["SampleLink"] = "Voorbeeldlink",
        ["PickFromImage"] = "Kleur kiezen uit een afbeelding",
        ["PickFromImageHint"] = "Maak met het knipprogramma een schermafdruk van de clubsite, plak die hier (Ctrl+V) of upload hem, en klik op een kleur in de afbeelding.",
        ["OrPasteSnip"] = "of plak een knipsel (Ctrl+V)",
        ["PickImageFailed"] = "Kon de afbeelding niet laden (mogelijk te groot).",
        ["CompetitionPeriod"] = "Huidige competitieperiode",
        ["PlayingDays"] = "Speeldagen",
        ["PlayingDaysDesc"] = "Selecteer de dagen waarop de club speelt en stel de starttijden in.",
        ["AddTime"] = "Tijd toevoegen",
        ["DefaultStartTime"] = "Standaard aanvangstijd",
        ["DefaultStartTimeDesc"] = "De aanvangstijd die wordt gebruikt als er geen specifieke tijd is ingesteld.",
        ["TournamentStartTimes"] = "Standaard aanvangstijden toernooi",
        ["TournamentStartTimesDesc"] = "De aanvangstijden die worden toegekend aan de hanchans bij het genereren van een toernooi.",
        ["AddStartTime"] = "Toevoegen",
        ["RemoveStartTime"] = "Verwijderen",
        ["SettingsSaved"] = "Instellingen opgeslagen!",
        ["DeleteAllData"] = "Alle gegevens verwijderen",
        ["DeleteAllDataDesc"] = "Verwijder alle leden, zittingen, toernooien en instellingen permanent.",
        ["DeleteAllDataEnterCode"] = "Voer ter bevestiging de volgende code in:",
        ["DeleteAllDataSuccess"] = "Alle gegevens zijn verwijderd!",

        // Workflow page
        ["Workflow"] = "Stappenplan",
        ["WorkflowDesc"] = "Volg de onderstaande stappen om een zitting voor te bereiden en af te ronden.",
        ["WfStep1Title"] = "Stap 1: Gegevens importeren",
        ["WfStep1Desc"] = "Importeer het bestand met de clubgegevens.",
        ["WfStep1Button"] = "Naar Gegevensbeheer",
        ["WfStep2Title"] = "Stap 2: Zitting instellen",
        ["WfStep2Desc"] = "Stel de aanwezigheid in, genereer de tafelindeling en sla de hanchans op.",
        ["WfStep2Button"] = "Naar Zitting",
        ["WfStep2aTitle"] = "Stap 2a: Indeling bekend maken",
        ["WfStep2aDesc"] = "Indeling naar het klembord kopiëren en in de appgroup plakken.",
        ["WfStepScoresTitle"] = "Scores invoeren",
        ["WfStepScoresDesc"] = "Voer de scores in voor alle hanchans.",
        ["WfStepScoresButton"] = "Naar Scores",
        ["WfStep3Title"] = "Stap 3: Gegevens exporteren",
        ["WfStep3Desc"] = "Exporteer de bijgewerkte gegevens naar de Downloads-map.",
        ["WfStep3TitleSaveAs"] = "Stap 3: Gegevens opslaan",
        ["WfStep3DescSaveAs"] = "Sla de bijgewerkte gegevens op.",
        ["WfStep3Button"] = "Naar Gegevensbeheer",
        ["WfStep4Title"] = "Stap 4: Clubgegevens terugzetten",
        ["WfStep4Desc"] = "Kopieer het geëxporteerde bestand uit de Downloads-map naar de map \"Competitiecommissie Tsumo 2025\".",
        ["ResetWorkflow"] = "Stappenplan resetten",
        ["ResetWorkflowHint"] = "Beschikbaar wanneer alle stappen zijn afgerond.",
        ["MarkCompleted"] = "Markeer als afgerond",
        ["MarkUncompleted"] = "Markeer als niet afgerond",
        ["BackToWorkflow"] = "Terug naar stappenplan",
        ["BackToWorkflowImportHint"] = "Importeer eerst een bestand.",
        ["BackToWorkflowExportHint"] = "Exporteer eerst de gegevens.",

        ["ExcludeFromOptimization"] = "Uitsluiten van indelingsoptimalisatie",
        ["ExcludedFromOptimization"] = "Uitgesloten",

        // Tournament
        ["Tournament"] = "Toernooi",
        ["Tournaments"] = "Toernooien",
        ["TournamentDesc"] = "Toernooien aanmaken en beheren.",
        ["ManageTournaments"] = "Toernooien beheren",
        ["CreateTournament"] = "Toernooi aanmaken",
        ["TournamentName"] = "Naam toernooi",
        ["TournamentDate"] = "Datum",
        ["NumberOfHanchans"] = "Aantal hanchans",
        ["Participants"] = "Deelnemers",
        ["AddParticipant"] = "Deelnemer toevoegen",
        ["EditNames"] = "Namen bewerken",
        ["ImportCsv"] = "CSV importeren",
        ["ExportCsv"] = "CSV exporteren",
        ["ParticipantName"] = "Naam",
        ["LeagueId"] = "Bondsnummer",
        ["ParticipantNumber"] = "Nr.",
        ["GenerateAllHanchans"] = "Alle hanchans genereren",
        ["RegenerateAllHanchans"] = "Opnieuw genereren",
        ["RegenerateConfirmTournament"] = "Dit toernooi heeft al een indeling. Opnieuw genereren?",
        ["RandomizeNumbers"] = "Nummers willekeurig toewijzen",
        ["ConfirmRandomize"] = "Dit wijst nieuwe willekeurige nummers toe aan alle deelnemers. Doorgaan?",
        ["ConfirmGenerateParticipants"] = "Dit vervangt alle huidige deelnemers. Doorgaan?",
        ["NeedAtLeast13"] = "Minimaal 13 deelnemers nodig.",
        ["GeneratePlayers"] = "Deelnemers genereren",
        ["Generate"] = "Genereren",
        ["Hanchan"] = "Hanchan",
        ["TournamentSaved"] = "Toernooi opgeslagen!",
        ["DeleteTournament"] = "Toernooi verwijderen",
        ["DeleteTournamentConfirm"] = "Weet je zeker dat je dit toernooi wilt verwijderen?",
        ["NoTournamentsYet"] = "Nog geen toernooien.",
        ["ThreePlayerDistribution"] = "3-spelertafel verdeling",
        ["CopyAllHanchans"] = "Alle hanchans kopiëren",
        ["OpenTournament"] = "Openen",
        ["BackToTournaments"] = "Terug naar toernooien",
        ["ParticipantCount"] = "deelnemers",
        ["HanchansCount"] = "hanchans",
        ["Guidesheets"] = "Gidsbriefjes",
        ["GuidesheetsDesc"] = "Genereer gidsbriefjes voor alle deelnemers.",
        ["IncludeNames"] = "Namen weergeven",
        ["PrintGuidesheets"] = "Afdrukken / Openen",
        ["DownloadGuidesheets"] = "Downloaden als HTML",
        ["Opponents"] = "Tegenstanders",

        // Scoring
        ["Scores"] = "Scores",
        ["StartingPoints"] = "Startpunten",
        ["EndPoints"] = "Eindpunten",
        ["Difference"] = "Verschil",
        ["Uma"] = "Uma",
        ["FinalScore"] = "Eindscore",
        ["StartShort"] = "Start",
        ["Advanced"] = "Geavanceerd",
        ["LoanShort"] = "Lening",
        ["EndShort"] = "Eind",
        ["DifferenceShort"] = "Verschil",
        ["DifferenceMicro"] = "Versch.",
        ["UmaShort"] = "Uma",
        ["PenaltyShort"] = "Straf",
        ["FinalScoreShort"] = "Totaal",
        ["InitialsShort"] = "Paraaf",
        ["ScoringLandingText"] = "Open de link die je organisator in WhatsApp heeft gedeeld om de scores voor je tafel in te vullen.",
        ["ScoringLandingHint"] = "Deze app werkt offline zodra je hem één keer hebt geopend.",
        ["ScoringInvalidLink"] = "Ongeldige of ontbrekende scorelink.",
        ["ScoringInvalidLinkHint"] = "Vraag je organisator om de link opnieuw te delen.",
        ["CopyResultLink"] = "Resultaatlink kopiëren",
        ["ClearScores"] = "Wissen",
        ["ClearScoresConfirm"] = "Scores wissen?",
        ["YesClear"] = "Ja, wissen",
        ["ResultReadyHint"] = "Plak de link terug in de WhatsApp-groep.",
        ["FillInScoresHint"] = "Vul de eindstanden in. Wanneer de scores kloppen wordt de deel-knop actief.",
        ["EnableExternalScoring"] = "Scoren via de scoring-app inschakelen",
        ["ActivateLogging"] = "Logboek inschakelen",
        ["ActivateLoggingHint"] = "Bewaart elke gescande/geplakte import en toont een Logboek-menu-item om ze te bekijken en te decoderen.",
        ["ScanLog"] = "Logboek",
        ["ScanLogEmpty"] = "Nog geen imports vastgelegd.",
        ["ScanLogDisabled"] = "Logboek is uitgeschakeld. Schakel het in bij Instellingen.",
        ["ScanLogClear"] = "Logboek wissen",
        ["ScanLogClearConfirm"] = "Het hele logboek wissen?",
        ["ScanLogDecode"] = "Decoderen",
        ["ScanLogHide"] = "Verbergen",
        ["ScanLogUnrecognized"] = "Niet-herkende invoer",
        ["ScanLogInvite"] = "Uitnodigingslink (geen resultaat)",
        ["ScanLogTableGone"] = "Tafel bestaat niet meer",
        ["ScanLogUnknownContext"] = "onbekende zitting",
        ["ScanLogContextId"] = "Zitting-ID",
        ["ScanLogCapturedAt"] = "Vastgelegd op",
        ["ScanLogMismatch"] = "De tafel komt niet meer overeen met dit resultaat (opnieuw ingedeeld?).",
        ["ReadyToScan"] = "Klaar om te scannen…",
        ["ScanningNow"] = "Bezig met scannen…",
        ["ScanFocusLost"] = "Niet actief — klik om te hervatten",
        ["CameraScan"] = "Camera scannen",
        ["HandScanner"] = "Handscanner",
        ["ImportChooseMethod"] = "Kies een invoermethode:",
        ["ShareScoringLink"] = "Scorelink delen",
        ["ImportScoreTitle"] = "Scores importeren",
        ["ImportScoreConfirm"] = "Onderstaande scores toevoegen aan deze tafel?",
        ["ImportScoreApply"] = "Toepassen",
        ["ImportScoreNoMatch"] = "Geen overeenkomende tafel gevonden in de opgeslagen zittingen.",
        ["ImportScoreApplied"] = "Scores geïmporteerd.",
        ["ImportScoreOverwriteWarning"] = "Deze tafel heeft al ingevoerde scores. Toepassen overschrijft die.",
        ["BackToSession"] = "Terug naar zitting",
        ["ImportResult"] = "Resultaat importeren",
        ["ImportResultPanelTitle"] = "Resultaatlink importeren",
        ["ImportResultPanelHint"] = "Plak hier de resultaatlink die je uit WhatsApp gekopieerd hebt.",
        ["ImportResultPlaceholder"] = "Scan, plak of typ een resultaatlink",
        ["ImportResultReading"] = "Klembord lezen…",
        ["CheckClipboard"] = "Klembord controleren",
        ["ImportResultErrorTruncated"] = "De scan was niet volledig — opnieuw scannen graag.",
        ["ImportResultNoneInClipboard"] = "Het klembord bevat geen resultaatlink. Kopieer eerst de link uit WhatsApp en probeer opnieuw.",
        ["Retry"] = "Opnieuw proberen",
        ["Next"] = "Volgende",
        ["ShowQrCode"] = "QR-code tonen",
        ["QrCodeTitle"] = "QR-code",
        ["QrCodeScoringSubtitle"] = "Scan deze code met de telefoon van de speler die de scores invult.",
        ["QrCodeResultSubtitle"] = "Scan deze code met de telefoon van de organisator om de scores te importeren.",
        ["QrCopiedToClipboard"] = "✅ QR-code naar klembord gekopieerd — plak hem in WhatsApp.",
        ["StatusExpl_Partial"] = "Er zijn al scores ingevuld, maar nog niet alle scores zijn compleet.",
        ["StatusExpl_Stale"] = "Een latere hanchan op deze datum heeft al scores, maar deze hanchan is nog niet volledig ingevuld.",
        ["StatusExpl_PartialAll"] = "Niet alle hanchans op deze datum hebben hun scores volledig ingevuld.",
        ["StatusExpl_StaleAll"] = "Een of meer eerdere hanchans hebben nog geen scores terwijl latere hanchans wel scores hebben.",
        ["ScanQrCode"] = "QR-code scannen",
        ["ScanQrHint"] = "Richt de camera op de QR-code van de speler.",
        ["ScanCameraError"] = "Kon de camera niet starten. Sta cameratoegang toe en probeer opnieuw.",
        ["ScanLooking"] = "Op zoek naar QR-code…",
        ["ScanStillLooking"] = "Nog steeds aan het zoeken. De QR-code wordt niet altijd herkend op een laptopcamera — probeer eens een andere afstand of meer licht.",
        ["ScanTipFraming"] = "Zorg dat de hele QR-code binnen het beeld past.",
        ["ScanTipFocus"] = "Houd de camera stil en zorg dat de QR-code scherp in beeld is.",
        ["ScanTipLight"] = "Vermijd schermreflecties; gelijkmatig licht helpt.",
        ["ScanTipLaptop"] = "Laptopcamera's stellen vaak slecht scherp op korte afstand — probeer ~30 cm afstand.",
        ["PickQrImage"] = "Afbeelding kiezen",
        ["FileDecoding"] = "Afbeelding analyseren…",
        ["FileScanNoQr"] = "Geen QR-code gevonden in de afbeelding. Probeer een scherpere foto of zorg dat de hele code in beeld staat.",
        ["ImportResultErrorNotResult"] = "Dit lijkt een scorelink (#p=…), niet de resultaatlink. Vraag de speler om de link te delen die zijn scoring-app heeft gegenereerd.",
        ["ImportResultNoMatchHint"] = "Geen overeenkomende tafel gevonden. Mogelijk is de hanchan opnieuw gegenereerd nadat de link was gedeeld.",
        ["ImportResultOverwritePrompt"] = "Deze tafel heeft al scores. Overschrijven?",
        ["YesOverwrite"] = "Ja, overschrijven",
        ["Preview"] = "Voorbeeld",
        ["Close"] = "Sluiten",
        ["ShareScoringLinkInstruction"] = "Tik om de scores in te voeren:",
        ["ShareResultInstruction"] = "Houd ingedrukt → Kopiëren → plak in de organiser-app:",
        ["PointsError"] = "Punten tellen niet op tot nul",
        ["MrX"] = "Mr. X",
        ["Deficit"] = "Tekort",
        ["Surplus"] = "Overschot",
        ["Points"] = "punten",
        ["Rankings"] = "Ranglijst",
        ["AllScores"] = "Alle scores",
        ["Rank"] = "#",
        ["TotalScore"] = "Totaal",
        ["WeeklyStartingPoints"] = "Startpunten clubavond",
        ["TournamentStartingPoints"] = "Startpunten toernooi",
        ["Uma4Players"] = "Uma 4-spelertafel",
        ["Uma3Players"] = "Uma 3-spelertafel",
        ["ScoringSettings"] = "Score-instellingen",
        ["ScoringSettingsDesc"] = "Standaardwaarden voor scores en Uma.",
        ["EnableScoreEntry"] = "Scores invoeren",
        ["Disabled"] = "Uitgeschakeld",
        ["ScoringOverrides"] = "Score-instellingen",
        ["ScoringOverridesDesc"] = "Overschrijf de standaard score-instellingen voor dit toernooi.",
        ["UseDefaults"] = "Gebruik standaardwaarden",

        ["Monday"] = "Maandag",
        ["Tuesday"] = "Dinsdag",
        ["Wednesday"] = "Woensdag",
        ["Thursday"] = "Donderdag",
        ["Friday"] = "Vrijdag",
        ["Saturday"] = "Zaterdag",
        ["Sunday"] = "Zondag",

        ["Month1"] = "januari",
        ["Month2"] = "februari",
        ["Month3"] = "maart",
        ["Month4"] = "april",
        ["Month5"] = "mei",
        ["Month6"] = "juni",
        ["Month7"] = "juli",
        ["Month8"] = "augustus",
        ["Month9"] = "september",
        ["Month10"] = "oktober",
        ["Month11"] = "november",
        ["Month12"] = "december",
    };

    // ── English ────────────────────────────────────────────
    private static readonly Dictionary<string, string> English = new()
    {
        // Mode selection
        ["SelectMode"] = "Select mode",
        ["WeeklyMode"] = "Club night",
        ["TournamentMode"] = "Tournament",
        ["WeeklyModeDesc"] = "Manage weekly sessions, members, and history.",
        ["TournamentModeDesc"] = "Tournaments with participants, assignments, and guidesheets.",
        ["SwitchMode"] = "Switch mode",

        // App update prompt (AppUpdateBanner)
        ["UpdateAvailable"] = "A new version is available. Close the app and reopen it to update.",
        ["UpdateDismiss"] = "Dismiss",

        // Tournament sub-nav
        ["TournamentParticipants"] = "Participants",
        ["TournamentAssignments"] = "Tables",
        ["TournamentGuidesheets"] = "Guidesheets",

        // Nav / Layout
        ["Home"] = "Home",
        ["Members"] = "Members",
        ["WeeklySession"] = "Session",
        ["History"] = "History",
        ["MeetingMatrix"] = "Meetings",
        ["CompetitionRanking"] = "Competition Ranking",
        ["ClubManager"] = "Club Manager",
        ["MahjongclubTsumo"] = "Mahjongclub Tsumo",

        // Home page
        ["WelcomeTo"] = "Welcome to Tsumo!",
        ["ManageMembers"] = "Manage Members",
        ["MembersDesc"] = "Add, edit, and manage club members.",
        ["StartSession"] = "Start Session",
        ["WeeklySessionDesc"] = "Track attendance and assign tables.",
        ["ViewHistory"] = "History",
        ["HistoryDesc"] = "View past sessions and player statistics.",
        ["ViewMatrix"] = "Meetings",
        ["MeetingMatrixDesc"] = "See how often each pair of players has met.",
        ["ViewCompetitionRanking"] = "Competition Ranking",
        ["CompetitionRankingDesc"] = "View average competition scores.",
        ["WorkflowHomeDesc"] = "Follow the step-by-step guide to prepare and finalize a session.",
        ["StartWorkflow"] = "Start workflow",

        // Members page
        ["ClubMembers"] = "Club Members",
        ["AddMember"] = "+ Add Member",
        ["EditMember"] = "Edit Member",
        ["AddNewMember"] = "Add New Member",
        ["Name"] = "Name",
        ["Email"] = "Email",
        ["Phone"] = "Phone",
        ["Active"] = "Active",
        ["Inactive"] = "Inactive",
        ["Joined"] = "Joined",
        ["Status"] = "Status",
        ["Actions"] = "Actions",
        ["Edit"] = "Edit",
        ["Remove"] = "Remove",
        ["Save"] = "Save",
        ["SaveAs"] = "Save as…",
        ["Cancel"] = "Cancel",
        ["NoMembersYet"] = "No members yet. Add your first club member!",
        ["ImportMembersCsv"] = "Import members (CSV)",
        ["ExportMembersCsv"] = "Export members (CSV)",
        ["SelectAllMembers"] = "Select all",
        ["DeselectAllMembers"] = "Deselect all",
        ["ExportSelected"] = "Export",
        ["selected"] = "selected",
        ["MembersImported"] = "members imported.",
        ["MembersImportError"] = "Invalid CSV format. Expected: Number;Name;LeagueId",
        ["Loading"] = "Loading...",
        ["Total"] = "Total",
        ["members"] = "members",
        ["active"] = "active",
        ["ExtraThreePlayerTables"] = "Extra 3-player tables",
        ["ExtraThreePlayerTablesDesc"] = "Number of 3-player tables not covered in hanchan history.",

        // Weekly Session page
        ["SessionDate"] = "Session Date",
        ["StartTime"] = "Start Time",
        ["SessionsOnDate"] = "Hanchans on this date",
        ["NewSession"] = "New Hanchan",
        ["AddHanchan"] = "Add Hanchan",
        ["NoTime"] = "No time",
        ["SwapPlayers"] = "Swap",
        ["Selected"] = "Selected",
        ["ClearSelection"] = "Clear selection",
        ["CopyToClipboard"] = "Copy to clipboard",
        ["Copied"] = "Copied!",
        ["Copy"] = "Copy",
        ["Print"] = "Print",
        ["Download"] = "Download",
        ["Export"] = "Export",
        ["ExportAssignments"] = "Export assignments",
        ["ExportScoresheets"] = "Export scoresheets",
        ["ExportRankings"] = "Export rankings",
        ["OpenPrint"] = "Open / Print",
        ["DownloadHtml"] = "Download as HTML",
        ["PrintScoresheets"] = "Print",
        ["DownloadScoresheets"] = "Download as HTML",
        ["Scoresheets"] = "Scoresheets",
        ["DeleteHanchan"] = "Delete Hanchan",
        ["DeleteHanchanConfirm"] = "Are you sure you want to delete this hanchan?",
        ["YesDelete"] = "Yes, delete",
        ["ConfirmDeletion"] = "Confirm deletion",
        ["Attendance"] = "Attendance",
        ["present"] = "present",
        ["of"] = "of",
        ["AllPresent"] = "All Present",
        ["AllAbsent"] = "All Absent",
        ["SearchMembers"] = "Search members...",
        ["GenerateTableAssignments"] = "Generate Tables",
        ["Regenerate"] = "Regenerate",
        ["CopyTables"] = "Copy Table Assignments",
        ["CopyFromHistory"] = "Copy from History",
        ["SelectSessionToCopy"] = "Select a session to copy",
        ["SaveHanchan"] = "Save Hanchan",
        ["TableAssignments"] = "Table Assignments",
        ["AssignmentsAndScores"] = "Assignments and scores",
        ["Assignments"] = "Assignments",
        ["Table"] = "Table",
        ["players"] = "players",
        ["Unknown"] = "Unknown",
        ["UnassignedPlayers"] = "player(s) could not be assigned to a table (not enough for a group of 3).",
        ["SessionSaved"] = "Session saved successfully!",
        ["PastSessionReadOnly"] = "This is a past session that has been finalized. It is read-only.",
        ["RegenerateConfirm"] = "This hanchan already has table assignments. Regenerate?",
        ["YesRegenerate"] = "Yes, regenerate",
        ["ChangeParticipantsWarning"] = "Table assignments will be reset when the number of participants changes.",
        ["ChangeAttendanceWarning"] = "Table assignments will be reset when attendance changes.",
        ["YesContinue"] = "Continue",
        ["AddMembersFirst"] = "No members registered yet.",
        ["AddMembersLink"] = "Add members first",
        ["NoMembersRegistered"] = "No members registered yet.",

        // History page
        ["SessionHistory"] = "Session History",
        ["GoTo"] = "Go to",
        ["NoSessionsYet"] = "No sessions recorded yet.",
        ["CreateFirstSession"] = "Create your first session",
        ["PresentPlayers"] = "Present Players",
        ["AbsentPlayers"] = "Absent Players",
        ["PlayerStatistics"] = "Player Statistics",
        ["Player"] = "Player",
        ["SessionsAttended"] = "Hanchans Attended",
        ["TimesAt3Table"] = "Times at 3-Player Table",
        ["TimesAt4Table"] = "Times at 4-Player Table",
        ["table"] = "table",
        ["tables"] = "tables",

        // Meeting Matrix page
        ["MeetingMatrixTitle"] = "Meetings",
        ["MeetingMatrixSubtitle"] = "How many times each pair of players has been at the same table.",
        ["CompetitionRankingTitle"] = "Competition Ranking",
        ["CompetitionRankingSubtitle"] = "Average score across all sessions that count towards the competition.",
        ["AverageScore"] = "Average",
        ["NoScoreData"] = "No scores have been entered yet.",
        ["ShowResultsPerDate"] = "Show results per date",
        ["NoSessionData"] = "No hanchan data yet.",
        ["Meetings"] = "Meetings",
        ["Pairs"] = "Pairs",

        // Data Management page
        ["DataManagement"] = "Data Management",
        ["ExportData"] = "Export Data",
        ["ExportDescription"] = "Export all members, sessions and tournaments to a file.",
        ["ExportToFile"] = "Export to file",
        ["ExportSuccess"] = "Data exported successfully!",
        ["ImportData"] = "Import Data",
        ["ImportDescription"] = "Import members, sessions and tournaments from a previously exported file. This replaces all current data.",
        ["ImportFromFile"] = "Import from file",
        ["ImportConfirm"] = "Warning: importing will replace all current data (members, sessions and tournaments). Are you sure?",
        ["YesImport"] = "Yes, import",
        ["ImportSuccess"] = "Data imported successfully!",
        ["InvalidFileFormat"] = "Invalid file format. Please use a previously exported Tsumo! file.",
        ["FileTooLarge"] = "File is too large (max 10 MB).",
        ["CurrentDataSummary"] = "Current data",
        ["Sessions"] = "Hanchans",

        // Settings page
        ["Settings"] = "Settings",
        ["SettingsTabClubEvent"] = "Club event",
        ["SettingsTabTournament"] = "Tournament",
        ["SettingsTabStyle"] = "Style",
        ["StyleIdentity"] = "Club identity",
        ["StyleColors"] = "Colours",
        ["StyleImages"] = "Images",
        ["BrandText"] = "Club name (top-left)",
        ["WebsiteUrl"] = "Website URL",
        ["WebsiteLinkLabel"] = "Website link text",
        ["PrimaryColor"] = "Primary colour",
        ["LinkColor"] = "Link colour",
        ["Logo"] = "Logo (top-left)",
        ["Banner"] = "Banner (home page)",
        ["UploadImage"] = "Upload",
        ["ImageUrl"] = "Or paste an image URL",
        ["ClearImage"] = "Clear image",
        ["ResetStyle"] = "Reset to neutral style",
        ["ResetStyleConfirm"] = "Reset all style settings to neutral?",
        ["YesReset"] = "Yes, reset",
        ["ExportStyle"] = "Export style",
        ["ImportStyle"] = "Import style",
        ["DiscardChanges"] = "Discard changes",
        ["CommitStyle"] = "Commit",
        ["YesCommit"] = "Yes, commit",
        ["CommitStyleConfirm"] = "Committing overwrites the saved style permanently. If you haven't exported the current style, it can't be restored. Commit anyway?",
        ["UnsavedStyleChanges"] = "Uncommitted style changes. Click Commit to keep them.",
        ["StyleSaved"] = "Style committed.",
        ["StyleImported"] = "Style loaded — click Commit to keep it.",
        ["InvalidStyleFile"] = "Invalid style file.",
        ["StylePreview"] = "Preview",
        ["StylePreviewDesc"] = "How your choices look. Changes show immediately; they're only kept when you click Commit.",
        ["SampleButton"] = "Sample button",
        ["SampleLink"] = "Sample link",
        ["PickFromImage"] = "Pick a colour from an image",
        ["PickFromImageHint"] = "Snip your club's website with the Snipping Tool, paste it here (Ctrl+V) or upload it, then click a colour in the image.",
        ["OrPasteSnip"] = "or paste a snip (Ctrl+V)",
        ["PickImageFailed"] = "Couldn't load the image (it may be too large).",
        ["CompetitionPeriod"] = "Current competition period",
        ["PlayingDays"] = "Playing Days",
        ["PlayingDaysDesc"] = "Select the days the club plays and set the starting times.",
        ["AddTime"] = "Add time",
        ["DefaultStartTime"] = "Default session start time",
        ["DefaultStartTimeDesc"] = "The start time used when no specific time is configured.",
        ["TournamentStartTimes"] = "Default tournament start times",
        ["TournamentStartTimesDesc"] = "The start times assigned to hanchans when generating a tournament.",
        ["AddStartTime"] = "Add",
        ["RemoveStartTime"] = "Remove",
        ["SettingsSaved"] = "Settings saved!",
        ["DeleteAllData"] = "Delete all data",
        ["DeleteAllDataDesc"] = "Permanently delete all members, sessions, tournaments, and settings.",
        ["DeleteAllDataEnterCode"] = "Enter the following code to confirm:",
        ["DeleteAllDataSuccess"] = "All data has been deleted!",

        // Workflow page
        ["Workflow"] = "Workflow",
        ["WorkflowDesc"] = "Follow the steps below to prepare and finalize a session.",
        ["WfStep1Title"] = "Step 1: Import data",
        ["WfStep1Desc"] = "Import the file with the club data.",
        ["WfStep1Button"] = "Go to Data Management",
        ["WfStep2Title"] = "Step 2: Set up the session",
        ["WfStep2Desc"] = "Administer attendance, generate table assignments, and save the session.",
        ["WfStep2Button"] = "Go to Session",
        ["WfStep2aTitle"] = "Step 2a: Publish the table assignments",
        ["WfStep2aDesc"] = "Copy the assignments to the clipboard and paste them in the app group.",
        ["WfStepScoresTitle"] = "Enter scores",
        ["WfStepScoresDesc"] = "Enter the scores for all hanchans.",
        ["WfStepScoresButton"] = "Go to Scores",
        ["WfStep3Title"] = "Step 3: Export data",
        ["WfStep3Desc"] = "Export the updated data to the Downloads folder.",
        ["WfStep3TitleSaveAs"] = "Step 3: Save the updated data",
        ["WfStep3DescSaveAs"] = "Save the updated data.",
        ["WfStep3Button"] = "Go to Data Management",
        ["WfStep4Title"] = "Step 4: Copy club data back",
        ["WfStep4Desc"] = "Copy the exported file from the Downloads folder to the \"Competitiecommissie Tsumo 2025\" folder.",
        ["ResetWorkflow"] = "Reset workflow",
        ["ResetWorkflowHint"] = "Available when all steps are completed.",
        ["MarkCompleted"] = "Mark as completed",
        ["MarkUncompleted"] = "Mark as uncompleted",
        ["BackToWorkflow"] = "Back to workflow",
        ["BackToWorkflowImportHint"] = "Import a file first.",
        ["BackToWorkflowExportHint"] = "Export the data first.",

        ["ExcludeFromOptimization"] = "Exclude from meeting optimization",
        ["ExcludedFromOptimization"] = "Excluded",

        // Tournament
        ["Tournament"] = "Tournament",
        ["Tournaments"] = "Tournaments",
        ["TournamentDesc"] = "Create and manage tournaments.",
        ["ManageTournaments"] = "Manage Tournaments",
        ["CreateTournament"] = "Create Tournament",
        ["TournamentName"] = "Tournament name",
        ["TournamentDate"] = "Date",
        ["NumberOfHanchans"] = "Number of hanchans",
        ["Participants"] = "Participants",
        ["AddParticipant"] = "Add participant",
        ["EditNames"] = "Edit names",
        ["ImportCsv"] = "Import CSV",
        ["ExportCsv"] = "Export CSV",
        ["ParticipantName"] = "Name",
        ["LeagueId"] = "League Id",
        ["ParticipantNumber"] = "No.",
        ["GenerateAllHanchans"] = "Generate all hanchans",
        ["RegenerateAllHanchans"] = "Regenerate",
        ["RegenerateConfirmTournament"] = "This tournament already has assignments. Regenerate?",
        ["RandomizeNumbers"] = "Randomize numbers",
        ["ConfirmRandomize"] = "This will assign new random numbers to all participants. Continue?",
        ["ConfirmGenerateParticipants"] = "This will replace all current participants. Continue?",
        ["NeedAtLeast13"] = "At least 13 participants required.",
        ["GeneratePlayers"] = "Generate players",
        ["Generate"] = "Generate",
        ["Hanchan"] = "Hanchan",
        ["TournamentSaved"] = "Tournament saved!",
        ["DeleteTournament"] = "Delete Tournament",
        ["DeleteTournamentConfirm"] = "Are you sure you want to delete this tournament?",
        ["NoTournamentsYet"] = "No tournaments yet.",
        ["ThreePlayerDistribution"] = "3-player table distribution",
        ["CopyAllHanchans"] = "Copy all hanchans",
        ["OpenTournament"] = "Open",
        ["BackToTournaments"] = "Back to tournaments",
        ["ParticipantCount"] = "participants",
        ["HanchansCount"] = "hanchans",
        ["Guidesheets"] = "Guidesheets",
        ["GuidesheetsDesc"] = "Generate guidesheets for all participants.",
        ["IncludeNames"] = "Include names",
        ["PrintGuidesheets"] = "Print / Open",
        ["DownloadGuidesheets"] = "Download as HTML",
        ["Opponents"] = "Opponents",

        // Scoring
        ["Scores"] = "Scores",
        ["StartingPoints"] = "Starting points",
        ["EndPoints"] = "End points",
        ["Difference"] = "Difference",
        ["Uma"] = "Uma",
        ["FinalScore"] = "Final score",
        ["Advanced"] = "Advanced",
        ["StartShort"] = "Start",
        ["LoanShort"] = "Loan",
        ["EndShort"] = "End",
        ["DifferenceShort"] = "Diff",
        ["DifferenceMicro"] = "Diff.",
        ["UmaShort"] = "Uma",
        ["PenaltyShort"] = "Penalty",
        ["FinalScoreShort"] = "Total",
        ["InitialsShort"] = "Initials",
        ["ScoringLandingText"] = "Open the link your organizer shared in WhatsApp to enter the scores for your table.",
        ["ScoringLandingHint"] = "This app works offline once you've opened it once.",
        ["ScoringInvalidLink"] = "Invalid or missing scoring link.",
        ["ScoringInvalidLinkHint"] = "Ask your organizer to share the link again.",
        ["CopyResultLink"] = "Copy result link",
        ["ClearScores"] = "Clear",
        ["ClearScoresConfirm"] = "Clear scores?",
        ["YesClear"] = "Yes, clear",
        ["ResultReadyHint"] = "Paste the link back into the WhatsApp group.",
        ["FillInScoresHint"] = "Fill in the end scores. The share button becomes active when the scores balance.",
        ["EnableExternalScoring"] = "Enable scoring through the scoring app",
        ["ActivateLogging"] = "Activate logging",
        ["ActivateLoggingHint"] = "Records every scanned/pasted import and adds a Log menu item to inspect and decode them.",
        ["ScanLog"] = "Log",
        ["ScanLogEmpty"] = "No imports captured yet.",
        ["ScanLogDisabled"] = "Logging is disabled. Enable it in Settings.",
        ["ScanLogClear"] = "Clear log",
        ["ScanLogClearConfirm"] = "Clear the entire log?",
        ["ScanLogDecode"] = "Decode",
        ["ScanLogHide"] = "Hide",
        ["ScanLogUnrecognized"] = "Unrecognized capture",
        ["ScanLogInvite"] = "Invite link (not a result)",
        ["ScanLogTableGone"] = "Table no longer exists",
        ["ScanLogUnknownContext"] = "unknown session",
        ["ScanLogContextId"] = "Session ID",
        ["ScanLogCapturedAt"] = "Captured at",
        ["ScanLogMismatch"] = "The table no longer matches this result (regenerated?).",
        ["ReadyToScan"] = "Ready to scan…",
        ["ScanningNow"] = "Scanning…",
        ["ScanFocusLost"] = "Not listening — click to resume",
        ["CameraScan"] = "Camera scan",
        ["HandScanner"] = "Hand scanner",
        ["ImportChooseMethod"] = "Choose an input method:",
        ["ShareScoringLink"] = "Share scoring link",
        ["ImportScoreTitle"] = "Import scores",
        ["ImportScoreConfirm"] = "Add the scores below to this table?",
        ["ImportScoreApply"] = "Apply",
        ["ImportScoreNoMatch"] = "No matching table found in saved sessions.",
        ["ImportScoreApplied"] = "Scores imported.",
        ["ImportScoreOverwriteWarning"] = "This table already has scores entered. Applying will overwrite them.",
        ["BackToSession"] = "Back to session",
        ["ImportResult"] = "Import result",
        ["ImportResultPanelTitle"] = "Import result link",
        ["ImportResultPanelHint"] = "Paste the result link you copied from WhatsApp.",
        ["ImportResultPlaceholder"] = "Scan, paste or type a result link",
        ["ImportResultReading"] = "Reading clipboard…",
        ["CheckClipboard"] = "Check clipboard",
        ["ImportResultErrorTruncated"] = "The scan was incomplete — please re-scan.",
        ["ImportResultNoneInClipboard"] = "The clipboard doesn't contain a result link. Copy the link from WhatsApp first, then retry.",
        ["Retry"] = "Retry",
        ["Next"] = "Next",
        ["ShowQrCode"] = "Show QR code",
        ["QrCodeTitle"] = "QR code",
        ["QrCodeScoringSubtitle"] = "Scan this with the phone of the player who will enter the scores.",
        ["QrCodeResultSubtitle"] = "Scan this with the organiser's phone to import the scores.",
        ["QrCopiedToClipboard"] = "✅ QR code copied to clipboard — paste it into WhatsApp.",
        ["StatusExpl_Partial"] = "Some scores are entered but not all are complete yet.",
        ["StatusExpl_Stale"] = "A later hanchan on this date has scores, but this one isn't fully entered yet.",
        ["StatusExpl_PartialAll"] = "Not all hanchans on this date have their scores fully entered.",
        ["StatusExpl_StaleAll"] = "One or more earlier hanchans are still empty while later ones already have scores.",
        ["ScanQrCode"] = "Scan QR code",
        ["ScanQrHint"] = "Aim the camera at the player's QR code.",
        ["ScanCameraError"] = "Couldn't start the camera. Allow camera access and try again.",
        ["ScanLooking"] = "Looking for QR code…",
        ["ScanStillLooking"] = "Still searching. Laptop cameras often struggle with QR codes — try a different distance or better lighting.",
        ["ScanTipFraming"] = "Make sure the entire QR code fits inside the frame.",
        ["ScanTipFocus"] = "Hold the camera steady and keep the QR code in focus.",
        ["ScanTipLight"] = "Avoid screen glare; even lighting helps.",
        ["ScanTipLaptop"] = "Laptop cameras often focus poorly up close — try ~30cm distance.",
        ["PickQrImage"] = "Choose image",
        ["FileDecoding"] = "Decoding image…",
        ["FileScanNoQr"] = "No QR code found in the image. Try a sharper photo or make sure the whole code is in view.",
        ["ImportResultErrorNotResult"] = "This looks like a scoring invite (#p=…), not a result link. Ask the player to share the link their scoring app produced.",
        ["ImportResultNoMatchHint"] = "No matching table found. The hanchan may have been regenerated after the link was shared.",
        ["ImportResultOverwritePrompt"] = "This table already has scores. Overwrite?",
        ["YesOverwrite"] = "Yes, overwrite",
        ["Preview"] = "Preview",
        ["Close"] = "Close",
        ["ShareScoringLinkInstruction"] = "Tap to enter the scores:",
        ["ShareResultInstruction"] = "Long-press → Copy → paste into the organiser app:",
        ["PointsError"] = "Points do not add up to zero",
        ["MrX"] = "Mr. X",
        ["Deficit"] = "Deficit",
        ["Surplus"] = "Surplus",
        ["Points"] = "points",
        ["Rankings"] = "Rankings",
        ["AllScores"] = "All scores",
        ["Rank"] = "#",
        ["TotalScore"] = "Total",
        ["WeeklyStartingPoints"] = "Weekly starting points",
        ["TournamentStartingPoints"] = "Tournament starting points",
        ["Uma4Players"] = "Uma 4-player table",
        ["Uma3Players"] = "Uma 3-player table",
        ["ScoringSettings"] = "Scoring settings",
        ["EnableScoreEntry"] = "Enter scores",
        ["Disabled"] = "Disabled",
        ["ScoringSettingsDesc"] = "Default values for scores and Uma.",
        ["ScoringOverrides"] = "Scoring settings",
        ["ScoringOverridesDesc"] = "Override the default scoring settings for this tournament.",
        ["UseDefaults"] = "Use defaults",

        ["Monday"] = "Monday",
        ["Tuesday"] = "Tuesday",
        ["Wednesday"] = "Wednesday",
        ["Thursday"] = "Thursday",
        ["Friday"] = "Friday",
        ["Saturday"] = "Saturday",
        ["Sunday"] = "Sunday",

        ["Month1"] = "January",
        ["Month2"] = "February",
        ["Month3"] = "March",
        ["Month4"] = "April",
        ["Month5"] = "May",
        ["Month6"] = "June",
        ["Month7"] = "July",
        ["Month8"] = "August",
        ["Month9"] = "September",
        ["Month10"] = "October",
        ["Month11"] = "November",
        ["Month12"] = "December",
    };
}
